/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminsRouteImport } from './routes/_authenticated/admins'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedIpeRouteImport } from './routes/_authenticated/ipe'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as ExamInfoExamIdRouteImport } from './routes/exam-info.$examId'
import { Route as ExamAttemptIdRouteImport } from './routes/exam.$attemptId'
import { Route as HistoryIndexRouteImport } from './routes/history.index'
import { Route as HistoryAttemptIdRouteImport } from './routes/history.$attemptId'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAttemptResultsAttemptIdRouteImport } from './routes/_authenticated/attempt-results.$attemptId'
import { Route as AuthenticatedExamsExamIdRouteImport } from './routes/_authenticated/exams/$examId'
import { Route as AuthenticatedExamsNewRouteImport } from './routes/_authenticated/exams/new'
import { Route as AuthenticatedResultsIndexRouteImport } from './routes/_authenticated/results.index'
import { Route as AuthenticatedResultsStudentIdRouteImport } from './routes/_authenticated/results.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminsRoute = AuthenticatedAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIpeRoute = AuthenticatedIpeRouteImport.update({
  id: '/ipe',
  path: '/ipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ExamInfoExamIdRoute = ExamInfoExamIdRouteImport.update({
  id: '/exam-info/$examId',
  path: '/exam-info/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamAttemptIdRoute = ExamAttemptIdRouteImport.update({
  id: '/exam/$attemptId',
  path: '/exam/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryAttemptIdRoute = HistoryAttemptIdRouteImport.update({
  id: '/history/$attemptId',
  path: '/history/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAttemptResultsAttemptIdRoute =
  AuthenticatedAttemptResultsAttemptIdRouteImport.update({
    id: '/attempt-results/$attemptId',
    path: '/attempt-results/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsExamIdRoute =
  AuthenticatedExamsExamIdRouteImport.update({
    id: '/exams/$examId',
    path: '/exams/$examId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsNewRoute = AuthenticatedExamsNewRouteImport.update({
  id: '/exams/new',
  path: '/exams/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsIndexRoute =
  AuthenticatedResultsIndexRouteImport.update({
    id: '/results/',
    path: '/results/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResultsStudentIdRoute =
  AuthenticatedResultsStudentIdRouteImport.update({
    id: '/results/$studentId',
    path: '/results/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/parent': typeof ParentRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admins': typeof AuthenticatedAdminsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ipe': typeof AuthenticatedIpeRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/exam-info/$examId': typeof ExamInfoExamIdRoute
  '/exam/$attemptId': typeof ExamAttemptIdRoute
  '/history/$attemptId': typeof HistoryAttemptIdRoute
  '/history/': typeof HistoryIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/attempt-results/$attemptId': typeof AuthenticatedAttemptResultsAttemptIdRoute
  '/exams/$examId': typeof AuthenticatedExamsExamIdRoute
  '/exams/new': typeof AuthenticatedExamsNewRoute
  '/results/$studentId': typeof AuthenticatedResultsStudentIdRoute
  '/results/': typeof AuthenticatedResultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/parent': typeof ParentRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admins': typeof AuthenticatedAdminsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ipe': typeof AuthenticatedIpeRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/exam-info/$examId': typeof ExamInfoExamIdRoute
  '/exam/$attemptId': typeof ExamAttemptIdRoute
  '/history/$attemptId': typeof HistoryAttemptIdRoute
  '/history': typeof HistoryIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/attempt-results/$attemptId': typeof AuthenticatedAttemptResultsAttemptIdRoute
  '/exams/$examId': typeof AuthenticatedExamsExamIdRoute
  '/exams/new': typeof AuthenticatedExamsNewRoute
  '/results/$studentId': typeof AuthenticatedResultsStudentIdRoute
  '/results': typeof AuthenticatedResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/parent': typeof ParentRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admins': typeof AuthenticatedAdminsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/ipe': typeof AuthenticatedIpeRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/exam-info/$examId': typeof ExamInfoExamIdRoute
  '/exam/$attemptId': typeof ExamAttemptIdRoute
  '/history/$attemptId': typeof HistoryAttemptIdRoute
  '/history/': typeof HistoryIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/attempt-results/$attemptId': typeof AuthenticatedAttemptResultsAttemptIdRoute
  '/_authenticated/exams/$examId': typeof AuthenticatedExamsExamIdRoute
  '/_authenticated/exams/new': typeof AuthenticatedExamsNewRoute
  '/_authenticated/results/$studentId': typeof AuthenticatedResultsStudentIdRoute
  '/_authenticated/results/': typeof AuthenticatedResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/parent'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admins'
    | '/dashboard'
    | '/ipe'
    | '/students'
    | '/exam-info/$examId'
    | '/exam/$attemptId'
    | '/history/$attemptId'
    | '/history/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/attempt-results/$attemptId'
    | '/exams/$examId'
    | '/exams/new'
    | '/results/$studentId'
    | '/results/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/parent'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admins'
    | '/dashboard'
    | '/ipe'
    | '/students'
    | '/exam-info/$examId'
    | '/exam/$attemptId'
    | '/history/$attemptId'
    | '/history'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/attempt-results/$attemptId'
    | '/exams/$examId'
    | '/exams/new'
    | '/results/$studentId'
    | '/results'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/parent'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admins'
    | '/_authenticated/dashboard'
    | '/_authenticated/ipe'
    | '/_authenticated/students'
    | '/exam-info/$examId'
    | '/exam/$attemptId'
    | '/history/$attemptId'
    | '/history/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/attempt-results/$attemptId'
    | '/_authenticated/exams/$examId'
    | '/_authenticated/exams/new'
    | '/_authenticated/results/$studentId'
    | '/_authenticated/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ParentRoute: typeof ParentRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ExamInfoExamIdRoute: typeof ExamInfoExamIdRoute
  ExamAttemptIdRoute: typeof ExamAttemptIdRoute
  HistoryAttemptIdRoute: typeof HistoryAttemptIdRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admins': {
      id: '/_authenticated/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AuthenticatedAdminsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ipe': {
      id: '/_authenticated/ipe'
      path: '/ipe'
      fullPath: '/ipe'
      preLoaderRoute: typeof AuthenticatedIpeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/exam-info/$examId': {
      id: '/exam-info/$examId'
      path: '/exam-info/$examId'
      fullPath: '/exam-info/$examId'
      preLoaderRoute: typeof ExamInfoExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$attemptId': {
      id: '/exam/$attemptId'
      path: '/exam/$attemptId'
      fullPath: '/exam/$attemptId'
      preLoaderRoute: typeof ExamAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$attemptId': {
      id: '/history/$attemptId'
      path: '/history/$attemptId'
      fullPath: '/history/$attemptId'
      preLoaderRoute: typeof HistoryAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/attempt-results/$attemptId': {
      id: '/_authenticated/attempt-results/$attemptId'
      path: '/attempt-results/$attemptId'
      fullPath: '/attempt-results/$attemptId'
      preLoaderRoute: typeof AuthenticatedAttemptResultsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/$examId': {
      id: '/_authenticated/exams/$examId'
      path: '/exams/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof AuthenticatedExamsExamIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/new': {
      id: '/_authenticated/exams/new'
      path: '/exams/new'
      fullPath: '/exams/new'
      preLoaderRoute: typeof AuthenticatedExamsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results/': {
      id: '/_authenticated/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof AuthenticatedResultsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results/$studentId': {
      id: '/_authenticated/results/$studentId'
      path: '/results/$studentId'
      fullPath: '/results/$studentId'
      preLoaderRoute: typeof AuthenticatedResultsStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminsRoute: typeof AuthenticatedAdminsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIpeRoute: typeof AuthenticatedIpeRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedAttemptResultsAttemptIdRoute: typeof AuthenticatedAttemptResultsAttemptIdRoute
  AuthenticatedExamsExamIdRoute: typeof AuthenticatedExamsExamIdRoute
  AuthenticatedExamsNewRoute: typeof AuthenticatedExamsNewRoute
  AuthenticatedResultsStudentIdRoute: typeof AuthenticatedResultsStudentIdRoute
  AuthenticatedResultsIndexRoute: typeof AuthenticatedResultsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminsRoute: AuthenticatedAdminsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIpeRoute: AuthenticatedIpeRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
  AuthenticatedAttemptResultsAttemptIdRoute:
    AuthenticatedAttemptResultsAttemptIdRoute,
  AuthenticatedExamsExamIdRoute: AuthenticatedExamsExamIdRoute,
  AuthenticatedExamsNewRoute: AuthenticatedExamsNewRoute,
  AuthenticatedResultsStudentIdRoute: AuthenticatedResultsStudentIdRoute,
  AuthenticatedResultsIndexRoute: AuthenticatedResultsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ParentRoute: ParentRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ExamInfoExamIdRoute: ExamInfoExamIdRoute,
  ExamAttemptIdRoute: ExamAttemptIdRoute,
  HistoryAttemptIdRoute: HistoryAttemptIdRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
